/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2017-12-01 10:19:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import metier.*;

public final class mapage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"erreur.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n");
      out.write("\t<title> MaPage </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
 	
	Connection con=null;
	Statement stmt;
	Class.forName("org.postgresql.Driver"); 
	String url = "jdbc:postgresql://psqlserv/n3p1";
	String nom = "marchant";
	String mdp = "moi";

	con = DriverManager.getConnection(url,nom,mdp);
	stmt = con.createStatement();

	String nomTable="personne";
	String sql= "select * from "+nomTable;
	ResultSet rs = stmt.executeQuery(sql);
		// ResultSetMetaData metaData = rs.getMetaData();
	JeuPileOuFace jeu=new JeuPileOuFace();
	jeu.init();
	Personne p=(Personne)session.getAttribute( "personne" );
	if(p==null){
		p=new Personne();
	}
	session.setAttribute( "personne", p );
	
      out.write("\n");
      out.write("\t\t<!-- <table><tr><th>id</th><th>nom</th><th>prenom</th></tr>\n");
      out.write("\n");
      out.write("\t");

		while(rs.next()){
	 
      out.write("\n");
      out.write("\t \t<tr><td>");
      out.print(rs.getString("id"));
      out.write("</td><td>");
      out.print(rs.getString("nom"));
      out.write("</td><td>");
      out.print(rs.getString("prenom"));
      out.write("</td></tr>\n");
      out.write("\t ");

	 	}
	 
      out.write("\n");
      out.write("\t</table> -->\n");
      out.write("\t");
out.println(p);
      out.write("\n");
      out.write("\t<h1>Vous: ");
      out.print(jeu.getPointsHumain());
      out.write("; ordinateur: ");
      out.print(jeu.getPointsOrdi());
      out.write("</h1>\n");
      out.write("\t");

	for (int i=1;i<=9;i++){
		out.println(i);
      out.write("</br>");
}
	
      out.write("\n");
      out.write("\tavec quelques accents à é è ù\n");
      out.write("\t");
con.close();
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
