/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2018-01-12 09:49:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class synthese_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


		String libE="Aucune sélection";
		String desE="Aucune sélection";
		int pnoE=-1;
		String libP="Aucune sélection";
		String desP="Aucune sélection";
		int pnoP=-1;
		String libD="Aucune sélection";
		String desD="Aucune sélection";
		int pnoD=-1;
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"erreur.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n");
      out.write("\t<title> Menu </title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      out.write('\n');
      out.write('	');
 	
	Connection con=null;
	Statement stmt;
	Class.forName("org.postgresql.Driver"); 
	String url = "jdbc:postgresql://psqlserv/n3p1";
	String nom = "marchant";
	String mdp = "moi";

	con = DriverManager.getConnection(url,nom,mdp);
	stmt = con.createStatement();

	String tmp = request.getParameter("type");
	char type;
	if(tmp==null){
		type='E';
	}else{
		type=tmp.charAt(0);
	}

	String nomTable="Plats";
	String sql= "select * from "+nomTable;
	ResultSet rs = stmt.executeQuery(sql);
	
	
      out.write('\n');
      out.write('\n');
      out.write('	');
 while(rs.next()){
		int pno=Integer.valueOf(rs.getString("pno"));
		String nomPlat=rs.getString("libelle");
		String descriptionPlat=rs.getString("description");

		int choixE=-1;
		int choixP=-1;
		int choixD=-1;

		Object tmp0=session.getAttribute("choixE");
		if(tmp0!=null){choixE=(int)tmp0;}

		Object tmp1=session.getAttribute("choixP");
		if(tmp1!=null){choixP=(int)tmp1;}

		Object tmp2=session.getAttribute("choixD");
		if(tmp2!=null){choixD=(int)tmp2;}
			
		
		if(choixE==pno){
			pnoE=pno;
			libE=nomPlat;
			desE=descriptionPlat;
		}else if(choixP==pno){
			libP=nomPlat;
			desP=descriptionPlat;
			pnoP=pno;
		}else if(choixD==pno){
			libD=nomPlat;
			desD=descriptionPlat;	
			pnoD=pno;
		}
	}
      out.write("\n");
      out.write("<p>\n");
      out.write("\n");
      out.write("Entrée:</br>");
      out.print(libE);
      out.write("</br>\n");
      out.write("Description:</br>");
      out.print(desE);
      out.write("</br></br>\n");
      out.write("Plat de résistance:</br>");
      out.print(libP);
      out.write("</br>\n");
      out.write("Description:</br>");
      out.print(desP);
      out.write("</br></br>\n");
      out.write("Dessert:</br>");
      out.print(libD);
      out.write("</br>\n");
      out.write("Description:</br>");
      out.print(desD);
      out.write("</br>\n");
      out.write("\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<form method=\"post\" action=\"./servlet/Enregistrer?pnoE=");
      out.print(pnoE);
      out.write("&pnoP=");
      out.print(pnoP);
      out.write("&pnoD=");
      out.print(pnoD);
      out.write("\">\n");
      out.write("\t<input type=\"email\" class=\"form-control\" name=\"mail\" aria-describedby=\"emailHelp\" placeholder=\"Enter email\">\n");
      out.write("\t<input type=\"date\" placeholder=\"Enter date\" name=\"date\">\n");
      out.write("\t<input type=\"submit\" value=\"Enregistrer\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<a href=\"plats.jsp\">retourner à la sélection de plats</a>\n");
      out.write("\n");
      out.write("\t");
con.close();
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
